[package]
name = "shuttlings-cch24"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { version = "3.1.5", features = ["test"] }
shuttle-poem = "0.49.0"
shuttle-runtime = "0.49.0"
serde = { version = "1.0.215", features = ["derive"] }

[dev-dependencies]
tokio = "1.41.1"
